### PR TITLE
Profile display and basic editing

### PR DESCRIPTION
**Pull request by CloneOrNot**
Open Task:
- Validation of edit
- Editing/ Save of Image

### CODE REVIEW

**Comment by rahilchughtai** [comment]
`main.a2fdeb76d9c07ab4.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'country')`

**Comment by rahilchughtai** [comment]
I think we can make the auth service cleaner, so I will restructure it a bit

**Comment by rahilchughtai** [comment]
Google login maybe be an unnecessary feature...he wont use it so maybe we can remove it at some point if it causes more complications and work

**Comment by CloneOrNot** [comment]
Agreed, removing it would make a lot of things easier in the code (service, login and profile) and we can also take a DB field out (providerinfo?). But would be usefull if we implement the new Login process first (which can be done by reusing the profile page as tmp login page).

**Comment by rahilchughtai** [comment]
I made some adjustments and tried to refactor a bit. Can still be made more modular and more reusable in the future but this should be ok for now. Please test if it works. Maybe delete account and try fresh login too, to make sure everything works. 

Things to check

- localstorage being in synch with firestore
- properties updating in both local and firestore when changing


Open tasks are more refactoring and maybe some more input validation. Would be nicer if some auth service functions werent of parameter type any but angular makes it hard because of optional fields.

**Pull request merged**
